# Copyright (c) HashiCorp, Inc.
# SPDX-License-Identifier: BUSL-1.1

apiVersion: v2
name: vault-secrets-operator
version: 0.4.1
appVersion: "0.4.1"
kubeVersion: ">=1.22.0-0"
description: Official Vault Secrets Operator Chart
type: application
sources:
  - https://github.com/hashicorp/vault-secrets-operator
