# Copyright (c) HashiCorp, Inc.
# SPDX-License-Identifier: BUSL-1.1

apiVersion: v2
name: vault-secrets-operator
version: 0.6.0
appVersion: "0.6.0"
kubeVersion: ">=1.21.0-0"
description: Official Vault Secrets Operator Chart
type: application
sources:
  - https://github.com/hashicorp/vault-secrets-operator
