{{/*
# Copyright (c) HashiCorp, Inc.
# SPDX-License-Identifier: BUSL-1.1
*/}}

apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "vso.chart.fullname" . }}-manager-config
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/component: controller-manager
  {{- include "vso.chart.labels" . | nindent 4 }}
data:
  controller_manager_config.yaml: |
    apiVersion: controller-runtime.sigs.k8s.io/v1beta1
    health:
      healthProbeBindAddress: {{ .Values.controller.controllerConfigMapYaml.health.healthProbeBindAddress | quote }}
    kind: ControllerManagerConfig
    leaderElection:
      leaderElect: {{ .Values.controller.controllerConfigMapYaml.leaderElection.leaderElect }}
      resourceName: {{ .Values.controller.controllerConfigMapYaml.leaderElection.resourceName | quote }}
    metrics:
      bindAddress: {{ .Values.controller.controllerConfigMapYaml.metrics.bindAddress | quote }}
    webhook:
      port: {{ .Values.controller.controllerConfigMapYaml.webhook.port }}
