# Copyright (c) HashiCorp, Inc.
# SPDX-License-Identifier: MPL-2.0

apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "chart.fullname" . }}-manager-config
  namespace: {{ .Release.Namespace }}
  labels:
    component: manager-config 
  {{- include "chart.labels" . | nindent 4 }}
data:
  controller_manager_config.yaml: |
    apiVersion: controller-runtime.sigs.k8s.io/v1alpha1
    health:
      healthProbeBindAddress: {{ .Values.managerConfig.controllerManagerConfigYaml.health.healthProbeBindAddress | quote }}
    kind: ControllerManagerConfig
    leaderElection:
      leaderElect: {{ .Values.managerConfig.controllerManagerConfigYaml.leaderElection.leaderElect }}
      resourceName: {{ .Values.managerConfig.controllerManagerConfigYaml.leaderElection.resourceName | quote }}
    metrics:
      bindAddress: {{ .Values.managerConfig.controllerManagerConfigYaml.metrics.bindAddress | quote }}
    webhook:
      port: {{ .Values.managerConfig.controllerManagerConfigYaml.webhook.port }}
