# Copyright IBM Corp. 2022, 2026
# SPDX-License-Identifier: BUSL-1.1

contact_links:
  - name: Ask a question
    url: https://discuss.hashicorp.com/c/vault
    about: For increased visibility, please post questions on the discussion forum, and tag with `k8s`
