# Copyright (c) 2022 HashiCorp, Inc.
# SPDX-License-Identifier: MPL-2.0

apiVersion: scorecard.operatorframework.io/v1alpha3
kind: Configuration
metadata:
  name: config
stages:
- parallel: true
  tests: []
