# Copyright IBM Corp. 2022, 2025
# SPDX-License-Identifier: BUSL-1.1

apiVersion: scorecard.operatorframework.io/v1alpha3
kind: Configuration
metadata:
  name: config
stages:
- parallel: true
  tests: []
