# Copyright (c) HashiCorp, Inc.
# SPDX-License-Identifier: BUSL-1.1

apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: |-
      [
        {
          "apiVersion": "secrets.hashicorp.com/v1beta1",
          "kind": "VaultConnection",
          "metadata": {
            "name": "vaultconnection-sample",
            "namespace": "tenant-1"
          },
          "spec": {
            "address": "http://vault.vault.svc.cluster.local:8200"
          }
        },
        {
          "apiVersion": "secrets.hashicorp.com/v1beta1",
          "kind": "VaultAuth",
          "metadata": {
            "name": "vaultauth-sample",
            "namespace": "tenant-1"
          },
          "spec": {
            "vaultConnectionRef": "vaultconnection-sample",
            "method": "kubernetes",
            "mount": "kubernetes",
            "kubernetes": {
              "role": "sample",
              "serviceAccount": "default"
            }
          }
        },
        {
          "apiVersion": "secrets.hashicorp.com/v1beta1",
          "kind": "VaultStaticSecret",
          "metadata": {
            "name": "vaultstaticsecret-sample",
            "namespace": "tenant-1"
          },
          "spec": {
            "vaultAuthRef": "vaultauth-sample",
            "mount": "kvv2",
            "type": "kv-v2",
            "path": "secret",
            "refreshAfter": "5s",
            "destination": {
              "create": true,
              "name": "secret1"
            }
          }
        }
      ]
    capabilities: Seamless Upgrades
    categories: Security
    containerImage: registry.connect.redhat.com/hashicorp/vault-secrets-operator
    description: The Vault Secrets Operator (VSO) allows Pods to consume Vault secrets
      natively from Kubernetes Secrets.
    features.operators.openshift.io/cnf: "false"
    features.operators.openshift.io/cni: "false"
    features.operators.openshift.io/csi: "false"
    features.operators.openshift.io/disconnected: "true"
    features.operators.openshift.io/fips-compliant: "false"
    features.operators.openshift.io/proxy-aware: "true"
    features.operators.openshift.io/tls-profiles: "false"
    features.operators.openshift.io/token-auth-aws: "false"
    features.operators.openshift.io/token-auth-azure: "false"
    features.operators.openshift.io/token-auth-gcp: "false"
    repository: https://github.com/hashicorp/vault-secrets-operator
    support: HashiCorp
  name: vault-secrets-operator.v0.0.0-dev
  namespace: placeholder
spec:
  apiservicedefinitions: {}
  customresourcedefinitions:
    owned:
    - description: HCPAuth is the Schema for the hcpauths API
      displayName: HCPAuth
      kind: HCPAuth
      name: hcpauths.secrets.hashicorp.com
      version: v1beta1
    - description: HCPVaultSecretsApp is the Schema for the hcpvaultsecretsapps API
      displayName: HCPVault Secrets App
      kind: HCPVaultSecretsApp
      name: hcpvaultsecretsapps.secrets.hashicorp.com
      version: v1beta1
    - description: SecretTransformation is the Schema for the secrettransformations
        API
      displayName: Secret Transformation
      kind: SecretTransformation
      name: secrettransformations.secrets.hashicorp.com
      version: v1beta1
    - description: VaultAuth is the Schema for the vaultauths API
      displayName: Vault Auth
      kind: VaultAuth
      name: vaultauths.secrets.hashicorp.com
      version: v1beta1
    - description: VaultConnection is the Schema for the vaultconnections API
      displayName: Vault Connection
      kind: VaultConnection
      name: vaultconnections.secrets.hashicorp.com
      version: v1beta1
    - description: VaultDynamicSecret is the Schema for the vaultdynamicsecrets API
      displayName: Vault Dynamic Secret
      kind: VaultDynamicSecret
      name: vaultdynamicsecrets.secrets.hashicorp.com
      version: v1beta1
    - description: VaultPKISecret is the Schema for the vaultpkisecrets API
      displayName: Vault PKISecret
      kind: VaultPKISecret
      name: vaultpkisecrets.secrets.hashicorp.com
      version: v1beta1
    - description: VaultStaticSecret is the Schema for the vaultstaticsecrets API
      displayName: Vault Static Secret
      kind: VaultStaticSecret
      name: vaultstaticsecrets.secrets.hashicorp.com
      version: v1beta1
  description: |-
    The Vault Secrets Operator (VSO) allows Pods to consume Vault secrets
    natively from Kubernetes Secrets.

    ## Overview

    The Vault Secrets Operator operates by watching for changes to its supported set of Custom Resource Definitions (CRD).
    Each CRD provides the specification required to allow the *Operator* to synchronize a Vault Secrets to a Kubernetes Secret.
    The *Operator* writes the *source* Vault secret data directly to the *destination* Kubernetes Secret, ensuring that any
    changes made to the *source* are replicated to the *destination* over its lifetime. In this way, an application only needs
    to have access to the *destination* secret in order to make use of the secret data contained within.

    See the developer docs for more info [here](https://developer.hashicorp.com/vault/docs/platform/k8s/vso), including
    [examples](https://developer.hashicorp.com/vault/docs/platform/k8s/vso/examples) and a
    [tutorial](https://developer.hashicorp.com/vault/tutorials/kubernetes/vault-secrets-operator)
    for getting started.
  displayName: Vault Secrets Operator
  icon:
  - base64data: PHN2ZyBpZD0iTE9HT1MiIHhtbG5zPSJodHRwOi8vd3d3LnczLm9yZy8yMDAwL3N2ZyIgdmlld0JveD0iMCAwIDE4MCAyNTgiPjxwYXRoIGQ9Ik02Mi4xNSwxOTguMTdoNi43Nkw1OC42NCwyMzIuNTZINDlMMzguNzYsMTk4LjE3aDYuNzZsOC4zMiwyOC42NloiLz48cGF0aCBkPSJNODcuNywyMzIuNTZIODIuNTRsLS40Ni0xLjcxYTEzLjc2LDEzLjc2LDAsMCwxLTcuNDksMi4yMmMtNC41OSwwLTYuNTYtMy4xNS02LjU2LTcuNDgsMC01LjExLDIuMjItNy4wOCw3LjMzLTcuMDhoNnYtMi42M2MwLTIuNzktLjc3LTMuNzctNC44LTMuNzdhMzQuNzgsMzQuNzgsMCwwLDAtNywuNzhsLS43Ny00LjhhMzIuNDYsMzIuNDYsMCwwLDEsOC42Mi0xLjE5YzcuOSwwLDEwLjIyLDIuNzksMTAuMjIsOS4wOVptLTYuMy05LjVINzYuNzZjLTIuMDcsMC0yLjYzLjU3LTIuNjMsMi40OCwwLDEuNzUuNTYsMi41MywyLjUzLDIuNTNhOS44OSw5Ljg5LDAsMCwwLDQuNzQtMS4yOVoiLz48cGF0aCBkPSJNOTcuNjIsMjA3LjQxVjIyNWMwLDEuMzQuNTYsMiwyLDJhMTcuMzksMTcuMzksMCwwLDAsNi41Ni0yLjEyVjIwNy40MWg2LjI5djI1LjE1aC00LjhsLS42Mi0yLjEyQTI1LjE0LDI1LjE0LDAsMCwxLDk3LDIzMy4wN2MtNC4xOSwwLTUuNjgtMi45NC01LjY4LTcuNDNWMjA3LjQxWiIvPjxwYXRoIGQ9Ik0xMTUuODQsMjMyLjU2VjE5Ny4xNGw2LjMtLjg4djM2LjNaIi8+PHBhdGggZD0iTTE0MC45MywyMzIuMDlhMTcuMzksMTcuMzksMCwwLDEtNS41MywxYy00LjU5LDAtNi45MS0yLjE2LTYuOTEtNi42NnYtMTRoLTMuNzd2LTVoMy43N3YtNi4yNGw2LjMtLjg4djcuMTJoNi40NWwtLjQxLDVoLTZ2MTMuMTdhMiwyLDAsMCwwLDIuMjcsMi4yMiwxMi4xNywxMi4xNywwLDAsMCwzLjE1LS41MloiLz48cGF0aCBkPSJNNDUuNDYsMTg5Ljc0di00LjgzSDQxLjA1djQuODNIMzguNzlWMTc4LjE1aDIuMjZWMTgzaDQuNDF2LTQuODZoMi4yNnYxMS41OVptMTAuNTIsMEg1NC4xOWwtLjE2LS41N2E0Ljg1LDQuODUsMCwwLDEtMi41OS43NGMtMS41OSwwLTIuMjctMS0yLjI3LTIuNDksMC0xLjcuNzctMi4zNSwyLjU0LTIuMzVINTMuOHYtLjg4YzAtLjkyLS4yNy0xLjI1LTEuNjYtMS4yNWExMi4yOCwxMi4yOCwwLDAsMC0yLjQyLjI2bC0uMjctMS42YTExLjkzLDExLjkzLDAsMCwxLDMtLjRjMi43NCwwLDMuNTQuOTMsMy41NCwzWm0tMi4xOC0zLjE2SDUyLjE5Yy0uNzEsMC0uOTEuMTktLjkxLjgzcy4yLjg0Ljg3Ljg0YTMuNTgsMy41OCwwLDAsMCwxLjY1LS40M1ptNi43NSwzLjMzYTEwLjQxLDEwLjQxLDAsMCwxLTMtLjQ4bC4zLTEuNmExMCwxMCwwLDAsMCwyLjYuMzdjMSwwLDEuMTEtLjIxLDEuMTEtLjg1cy0uMTEtLjc3LTEuNTItMS4xYy0yLjEzLS40OS0yLjM4LTEtMi4zOC0yLjYycy43Ny0yLjQzLDMuMjUtMi40M2ExMS44LDExLjgsMCwwLDEsMi42MS4zbC0uMjEsMS42NmExNiwxNiwwLDAsMC0yLjQtLjI0Yy0uOTUsMC0xLjExLjIxLTEuMTEuNzIsMCwuNjcuMDYuNzIsMS4yNCwxLDIuNDMuNjIsMi42Ni45MiwyLjY2LDIuNjRTNjMuMTgsMTg5LjkxLDYwLjU1LDE4OS45MVptMTAtLjE3VjE4My45YzAtLjQ1LS4yLS42Ny0uNy0uNjdhNi4wNyw2LjA3LDAsMCwwLTIuMjcuNzF2NS44SDY1LjM5VjE3OGwyLjE5LjMzVjE4MmE3LjkyLDcuOTIsMCwwLDEsMy4xOC0uODFjMS40NSwwLDIsMSwyLDIuNDh2Ni4wNlptNC05LjU1di0yaDIuMTh2MlptMCw5LjU1di04LjM2aDIuMTh2OC4zNlptMy45My04LjNjMC0yLjA5LDEuMjctMy4zMSw0LjI0LTMuMzFhMTQsMTQsMCwwLDEsMy4yMy4zOGwtLjI1LDEuODdhMTguMzYsMTguMzYsMCwwLDAtMi45MS0uMjljLTEuNTYsMC0yLjA2LjUxLTIuMDYsMS43M3Y0LjRjMCwxLjIyLjUsMS43MywyLjA2LDEuNzNhMTguMzYsMTguMzYsMCwwLDAsMi45MS0uMjlsLjI1LDEuODhhMTQsMTQsMCwwLDEtMy4yMy4zN2MtMywwLTQuMjQtMS4yMi00LjI0LTMuMzFabTEyLjMsOC40N2MtMywwLTMuOC0xLjU4LTMuOC0zLjNWMTg0LjVjMC0xLjcyLjgxLTMuMywzLjgtMy4zczMuNzksMS41OCwzLjc5LDMuM3YyLjExQzk0LjU4LDE4OC4zMyw5My43NywxODkuOTEsOTAuNzksMTg5LjkxWm0wLTYuOTJjLTEuMTcsMC0xLjYxLjUtMS42MSwxLjQ0djIuMjVjMCwuOTUuNDQsMS40NSwxLjYxLDEuNDVzMS42MS0uNSwxLjYxLTEuNDV2LTIuMjVDOTIuNCwxODMuNDksOTIsMTgzLDkwLjc5LDE4M1ptOS45My4xNGExNi44NywxNi44NywwLDAsMC0yLjMsMS4yMnY1LjM5SDk2LjIzdi04LjM2aDEuODVsLjE0LjkyYTEwLDEwLDAsMCwxLDIuMjktMS4xWm04LjczLDMuODNjMCwxLjg1LS44NiwyLjk1LTIuODgsMi45NWExMi4zNCwxMi4zNCwwLDAsMS0yLjMzLS4yNHYzLjQybC0yLjE4LjMzdi0xMmgxLjc0bC4yMS43YTQuNzIsNC43MiwwLDAsMSwyLjc1LS44OGMxLjc2LDAsMi42OSwxLDIuNjksMi45MVptLTUuMjEuOTRhMTAuMDksMTAuMDksMCwwLDAsMS45My4yM2MuNzksMCwxLjEtLjM2LDEuMS0xLjEydi0yLjk1YzAtLjY5LS4yNy0xLjA3LTEuMDgtMS4wN2EzLjE0LDMuMTQsMCwwLDAtMiwuNzZaIi8+PHBhdGggZD0iTTI2LjI1LDI3LjgxLDg5Ljc3LDE1MS40NGw2NC0xMjMuNjNaTTc5Ljg5LDc2Ljg4SDY5Ljc3VjY2Ljc3SDc5Ljg5Wm0wLTE1LjE3SDY5Ljc3VjUxLjU5SDc5Ljg5Wk05NS4wNyw5Mi4wNkg4NVY4MS45NEg5NS4wN1ptMC0xNS4xOEg4NVY2Ni43N0g5NS4wN1ptMC0xNS4xN0g4NVY1MS41OUg5NS4wN1ptMTUuMDksMTUuMTdIMTAwVjY2Ljc3aDEwLjEyWk0xMDAsNjEuNzFWNTEuNTloMTAuMTJWNjEuNzFaIi8+PC9zdmc+
    mediatype: image/svg+xml
  install:
    spec:
      deployments: null
    strategy: ""
  installModes:
  - supported: false
    type: OwnNamespace
  - supported: false
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: true
    type: AllNamespaces
  keywords:
  - vault
  - security
  - secrets
  links:
  - name: Vault Secrets Operator
    url: https://github.com/hashicorp/vault-secrets-operator
  - name: Documentation
    url: https://developer.hashicorp.com/vault/docs/platform/k8s/vso
  maintainers:
  - email: support@hashicorp.com
    name: HashiCorp Support
  maturity: stable
  provider:
    name: HashiCorp
    url: https://www.hashicorp.com/
  version: 0.0.0-dev
