# Copyright IBM Corp. 2022, 2025
# SPDX-License-Identifier: BUSL-1.1

# The following patch adds a directive for certmanager to inject CA into the CRD
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    cert-manager.io/inject-ca-from: $(CERTIFICATE_NAMESPACE)/$(CERTIFICATE_NAME)
  name: hcpauths.secrets.hashicorp.com
