# Copyright (c) HashiCorp, Inc.
# SPDX-License-Identifier: BUSL-1.1

## Append samples you want in your CSV to this file as resources ##
resources:
- secrets_v1beta1_vaultstaticsecret.yaml
- secrets_v1beta1_vaultpkisecret.yaml
- secrets_v1beta1_vaultpkisecret_tls.yaml
- secrets_v1beta1_vaultauth.yaml
- secrets_v1beta1_vaultconnection.yaml
- secrets_v1beta1_vaultdynamicsecret.yaml
- secrets_v1beta1_hcpsecretsapp.yaml
- secrets_v1beta1_hcpauth.yaml
#+kubebuilder:scaffold:manifestskustomizesamples
