# Copyright (c) HashiCorp, Inc.
# SPDX-License-Identifier: MPL-2.0

apiVersion: secrets.hashicorp.com/v1beta1
kind: HCPAuth
metadata:
  labels:
    app.kubernetes.io/name: hcpauth
    app.kubernetes.io/instance: hcpauth-sample
    app.kubernetes.io/part-of: vault-secrets-operator
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: vault-secrets-operator
  name: hcpauth-sample
spec:
  # TODO(user): Add fields here
