# Copyright (c) HashiCorp, Inc.
# SPDX-License-Identifier: MPL-2.0

---
apiVersion: secrets.hashicorp.com/v1alpha1
kind: VaultPKI
metadata:
  namespace: tenant-1
  name: vaultpki-sample-tenant-1
spec:
  vaultAuthRef: vaultauth-sample
  namespace: tenant-1
  mount: pki
  name: default
  dest: pki1
  commonName: consul.example.com
  format: pem
  revoke: true
  clear: true
  expiryOffset: 5s
  ttl: 15s
#---
#apiVersion: secrets.hashicorp.com/v1alpha1
#kind: VaultPKI
#metadata:
#  namespace: tenant-2
#  name: vaultpki-sample-tenant-2
#spec:
#  namespace: cluster1/tenant-2
#  mount: pki
#  name: default
#  dest: pki1
#  commonName: consul.example.com
#  revoke: false
#  format: pem_bundle
