# Copyright IBM Corp. 2022, 2025
# SPDX-License-Identifier: BUSL-1.1

apiVersion: secrets.hashicorp.com/v1beta1
kind: SecretTransformation
metadata:
  labels:
    app.kubernetes.io/name: secrettransformation
    app.kubernetes.io/instance: secrettransformation-sample
    app.kubernetes.io/part-of: vault-secrets-operator
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: vault-secrets-operator
  name: secrettransformation-sample
spec:
  # TODO(user): Add fields here
