# Copyright IBM Corp. 2022, 2026
# SPDX-License-Identifier: BUSL-1.1

apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    release: kube-prometheus
  name: controller-manager-metrics-monitor
  namespace: system
