# Copyright (c) HashiCorp, Inc.
# SPDX-License-Identifier: MPL-2.0

apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    controller-gen.kubebuilder.io/version: v0.11.1
  creationTimestamp: null
  name: vaultdynamicsecrets.secrets.hashicorp.com
spec:
  group: secrets.hashicorp.com
  names:
    kind: VaultDynamicSecret
    listKind: VaultDynamicSecretList
    plural: vaultdynamicsecrets
    singular: vaultdynamicsecret
  scope: Namespaced
  versions:
  - name: v1alpha1
    schema:
      openAPIV3Schema:
        description: VaultDynamicSecret is the Schema for the vaultdynamicsecrets
          API
        properties:
          apiVersion:
            description: 'APIVersion defines the versioned schema of this representation
              of an object. Servers should convert recognized schemas to the latest
              internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
            type: string
          kind:
            description: 'Kind is a string value representing the REST resource this
              object represents. Servers may infer this from the endpoint the client
              submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
            type: string
          metadata:
            type: object
          spec:
            description: VaultDynamicSecretSpec defines the desired state of VaultDynamicSecret
            properties:
              destination:
                description: Destination provides configuration necessary for syncing
                  the Vault secret to Kubernetes.
                properties:
                  annotations:
                    additionalProperties:
                      type: string
                    description: Annotations to apply to the Secret. Requires Create
                      to be set to true.
                    type: object
                  create:
                    description: Create the destination Secret. If the Secret already
                      exists this should be set to false.
                    type: boolean
                  labels:
                    additionalProperties:
                      type: string
                    description: Labels to apply to the Secret. Requires Create to
                      be set to true.
                    type: object
                  name:
                    description: Name of the Secret
                    type: string
                  type:
                    description: Type of Kubernetes Secret. Requires Create to be
                      set to true. Defaults to Opaque.
                    type: string
                required:
                - name
                type: object
              mount:
                description: Mount path of the secret's engine in Vault.
                type: string
              namespace:
                description: Namespace where the secrets engine is mounted in Vault.
                type: string
              revoke:
                description: Revoke the credential when the resource is deleted.
                type: boolean
              role:
                description: Role in Vault to get the credentials for.
                type: string
              rolloutRestartTargets:
                description: RolloutRestartTargets should be configured whenever the
                  application(s) consuming the Vault secret does not support dynamically
                  reloading a rotated secret. In that case one, or more RolloutRestartTarget(s)
                  can be configured here. The Operator will trigger a "rollout-restart"
                  for each target whenever the Vault secret changes between reconciliation
                  events. See RolloutRestartTarget for more details.
                items:
                  description: "RolloutRestartTarget provides the configuration required
                    to perform a rollout-restart of the supported resources upon Vault
                    Secret rotation. The rollout-restart is triggered by patching
                    the target resource's 'spec.template.metadata.annotations' to
                    include 'vso.secrets.hashicorp.com/restartedAt' with a timestamp
                    value of when the trigger was executed. E.g. vso.secrets.hashicorp.com/restartedAt:
                    \"2023-03-23T13:39:31Z\" \n Supported resources: Deployment, DaemonSet,
                    StatefulSet"
                  properties:
                    kind:
                      enum:
                      - Deployment
                      - DaemonSet
                      - StatefulSet
                      type: string
                    name:
                      type: string
                  required:
                  - kind
                  - name
                  type: object
                type: array
              vaultAuthRef:
                description: VaultAuthRef to the VaultAuth resource If no value is
                  specified the Operator will default to the `default` VaultAuth,
                  configured in its own Kubernetes namespace.
                type: string
            required:
            - destination
            - mount
            - role
            type: object
          status:
            description: VaultDynamicSecretStatus defines the observed state of VaultDynamicSecret
            properties:
              lastRenewalTime:
                description: LastRenewalTime of the last, successful, secret lease
                  renewal,
                format: int64
                type: integer
              lastRuntimePodUID:
                description: LastRuntimePodUID used for tracking the transition from
                  one Pod to the next. It is used to mitigate the effects of a Vault
                  lease renewal storm.
                type: string
              secretLease:
                description: SecretLease for the Vault secret.
                properties:
                  duration:
                    description: LeaseDuration of the Vault secret.
                    type: integer
                  id:
                    description: ID of the Vault secret.
                    type: string
                  renewable:
                    description: Renewable Vault secret lease
                    type: boolean
                  requestID:
                    description: RequestID of the Vault secret request.
                    type: string
                required:
                - duration
                - id
                - renewable
                - requestID
                type: object
            required:
            - lastRenewalTime
            - secretLease
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}
