# Copyright (c) HashiCorp, Inc.
# SPDX-License-Identifier: MPL-2.0

# This kustomization.yaml is not intended to be run by itself,
# since it depends on service name and namespace that are out of this kustomize package.
# It should be run by config/default
resources:
- bases/secrets.hashicorp.com_vaultstaticsecrets.yaml
- bases/secrets.hashicorp.com_vaultpkisecrets.yaml
- bases/secrets.hashicorp.com_vaultauths.yaml
- bases/secrets.hashicorp.com_vaultconnections.yaml
- bases/secrets.hashicorp.com_vaultdynamicsecrets.yaml
- bases/secrets.hashicorp.com_hcpauths.yaml
#+kubebuilder:scaffold:crdkustomizeresource

patchesStrategicMerge:
# [WEBHOOK] To enable webhook, uncomment all the sections with [WEBHOOK] prefix.
# patches here are for enabling the conversion webhook for each CRD
#- patches/webhook_in_vaultstaticsecrets.yaml
#- patches/webhook_in_vaultpkisecrets.yaml
#- patches/webhook_in_vaultauths.yaml
#- patches/webhook_in_vaultconnections.yaml
#- patches/webhook_in_vaultdynamicsecrets.yaml
#- patches/webhook_in_hcpauths.yaml
#+kubebuilder:scaffold:crdkustomizewebhookpatch

# [CERTMANAGER] To enable cert-manager, uncomment all the sections with [CERTMANAGER] prefix.
# patches here are for enabling the CA injection for each CRD
#- patches/cainjection_in_vaultstaticsecrets.yaml
#- patches/cainjection_in_vaultpkisecrets.yaml
#- patches/cainjection_in_vaultauths.yaml
#- patches/cainjection_in_vaultconnections.yaml
#- patches/cainjection_in_vaultdynamicsecrets.yaml
#- patches/cainjection_in_hcpauths.yaml
#+kubebuilder:scaffold:crdkustomizecainjectionpatch

# the following config is for teaching kustomize how to do kustomization for CRDs.
configurations:
- kustomizeconfig.yaml
