# Copyright (c) HashiCorp, Inc.
# SPDX-License-Identifier: BUSL-1.1

---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    controller-gen.kubebuilder.io/version: v0.16.3
  name: secrettransformations.secrets.hashicorp.com
spec:
  group: secrets.hashicorp.com
  names:
    kind: SecretTransformation
    listKind: SecretTransformationList
    plural: secrettransformations
    singular: secrettransformation
  scope: Namespaced
  versions:
  - name: v1beta1
    schema:
      openAPIV3Schema:
        description: SecretTransformation is the Schema for the secrettransformations
          API
        properties:
          apiVersion:
            description: |-
              APIVersion defines the versioned schema of this representation of an object.
              Servers should convert recognized schemas to the latest internal value, and
              may reject unrecognized values.
              More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
            type: string
          kind:
            description: |-
              Kind is a string value representing the REST resource this object represents.
              Servers may infer this from the endpoint the client submits requests to.
              Cannot be updated.
              In CamelCase.
              More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
            type: string
          metadata:
            type: object
          spec:
            description: SecretTransformationSpec defines the desired state of SecretTransformation
            properties:
              excludes:
                description: |-
                  Excludes contains regex patterns used to filter top-level source secret data
                  fields for exclusion from the final K8s Secret data. These pattern filters are
                  never applied to templated fields as defined in Templates. They are always
                  applied before any inclusion patterns. To exclude all source secret data
                  fields, you can configure the single pattern ".*".
                items:
                  type: string
                type: array
              includes:
                description: |-
                  Includes contains regex patterns used to filter top-level source secret data
                  fields for inclusion in the final K8s Secret data. These pattern filters are
                  never applied to templated fields as defined in Templates. They are always
                  applied last.
                items:
                  type: string
                type: array
              sourceTemplates:
                description: |-
                  SourceTemplates are never included in the rendered K8s Secret, they can be
                  used to provide common template definitions, etc.
                items:
                  description: SourceTemplate provides source templating configuration.
                  properties:
                    name:
                      type: string
                    text:
                      description: |-
                        Text contains the Go text template format. The template
                        references attributes from the data structure of the source secret.
                        Refer to https://pkg.go.dev/text/template for more information.
                      type: string
                  required:
                  - text
                  type: object
                type: array
              templates:
                additionalProperties:
                  description: Template provides templating configuration.
                  properties:
                    name:
                      description: Name of the Template
                      type: string
                    text:
                      description: |-
                        Text contains the Go text template format. The template
                        references attributes from the data structure of the source secret.
                        Refer to https://pkg.go.dev/text/template for more information.
                      type: string
                  required:
                  - text
                  type: object
                description: |-
                  Templates maps a template name to its Template. Templates are always included
                  in the rendered K8s Secret with the specified key.
                type: object
            type: object
          status:
            description: SecretTransformationStatus defines the observed state of
              SecretTransformation
            properties:
              error:
                type: string
              valid:
                type: boolean
            required:
            - error
            - valid
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}
