# Copyright (c) HashiCorp, Inc.
# SPDX-License-Identifier: MPL-2.0

---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    controller-gen.kubebuilder.io/version: v0.11.1
  creationTimestamp: null
  name: vaultclientcaches.secrets.hashicorp.com
spec:
  group: secrets.hashicorp.com
  names:
    kind: VaultClientCache
    listKind: VaultClientCacheList
    plural: vaultclientcaches
    singular: vaultclientcache
  scope: Namespaced
  versions:
  - name: v1alpha1
    schema:
      openAPIV3Schema:
        description: VaultClientCache is the Schema for the vaultclientcaches API
        properties:
          apiVersion:
            description: 'APIVersion defines the versioned schema of this representation
              of an object. Servers should convert recognized schemas to the latest
              internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
            type: string
          kind:
            description: 'Kind is a string value representing the REST resource this
              object represents. Servers may infer this from the endpoint the client
              submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
            type: string
          metadata:
            type: object
          spec:
            description: VaultClientCacheSpec defines the desired state of VaultClientCache.
              It is reserved for internal tracking of Vault client/token instances.
            properties:
              cacheFetchInterval:
                default: 5000000000
                description: 'TODO: consider making this seconds instead'
                format: int64
                maximum: 10000000000
                type: integer
              cacheKey:
                description: CacheKey points to a record in the operator's internal
                  clientCache.
                type: string
              credentialProviderUID:
                description: CredentialProviderUID to validate against.
                type: string
              maxCacheMisses:
                default: 5
                description: MaxCacheMisses MaxCacheMisses before this custom resource
                  is no longer considered valid. All invalid VaultClientCache resources
                  will be deleted by the controller.
                maximum: 30
                type: integer
              renewalOffset:
                description: 'RenewalOffset relative to the TokenTTL. Should never
                  be set to a value greater than TokenTTL. If the value is 0, or unset,
                  the controller will apply its own offset when computing the horizon
                  for the token renewal. TODO: consider making this seconds instead'
                format: int64
                type: integer
              vaultAuthGeneration:
                description: VaultAuthGeneration to validate against.
                format: int64
                type: integer
              vaultAuthMethod:
                description: VaultAuthMethod to be used during cache restoration.
                type: string
              vaultAuthName:
                description: VaultAuthName to be used during cache restoration.
                type: string
              vaultAuthNamespace:
                description: VaultAuthNamespace to be used during cache restoration.
                type: string
              vaultAuthUID:
                description: VaultAuthUID to validate against.
                type: string
              vaultConnectionGeneration:
                description: VaultConnectionGeneration to validate against.
                format: int64
                type: integer
              vaultConnectionUID:
                description: VaultConnectionUID to validate against.
                type: string
              vaultTransitRef:
                description: VaultTransitRef is the name of a VaultTransit custom
                  resource that will be used for encryption/decryption of the cached
                  client.
                type: string
            required:
            - cacheKey
            - vaultAuthGeneration
            - vaultAuthMethod
            - vaultAuthName
            - vaultAuthNamespace
            - vaultAuthUID
            - vaultConnectionGeneration
            - vaultConnectionUID
            type: object
          status:
            description: VaultClientCacheStatus defines the observed state of VaultClientCache
            properties:
              cacheMisses:
                type: integer
              cacheSecretRef:
                description: RenewCount, or the number of token renewals completed.
                type: string
            required:
            - cacheMisses
            - cacheSecretRef
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}
